### ISSUE TITLE
The #obstructed? method  in chess_piece.rb only allows for straight lines

### ISSUE THREAD

**Issue by radiofreemattd** [KnightsOfTheRemoteTable/chess_app#48]
Is this going to be a problem when we start to work with the Knights?

**Comment by jonmast** [comment]
Knights cannot be blocked so I didn't intend for the obstructed? method to be called for them.

**Comment by radiofreemattd** [comment]
I think this is where our issues on "movability" are merging. I continue to think `obstructed?` does too much when it checks whether or not a move is "diagonal" - that aspect seems more properly located in whether or not a move is valid, as opposed to whether a route is obstructed.

If we take that out (by moving the logic down to the specific pieces), the separation of logic will become much more straightforward IMO and not as un-DRY as I think you might be imagining (but I could be wrong there). I definitely want @mscoutermarsh 's feedback and, honestly, I think this is the kind of discussion that would be most productive for a hangout in real time...we could go for hours back and forth. We just need to get in a hangout, have someone screenshare, branch, and try to create a spike that solves all this...

Free all day.

**Comment by radiofreemattd** [comment]
Put differently, I imagine `valid_move?` to have a more or less uniform interface that looks something like this for each piece:

1. Call `obstructed?` to make sure there are no obstructions between the location of the current piece and the proposed destination. No point in running the logic if we can bail out early because of an obstruction.

2. Implement the specific move logic for the piece - as an example - Bishops must move diagonally (i.e. x must equal y), including any length limitations.

**Comment by radiofreemattd** [comment]
I am going to close this issue out in favor of discussion in https://github.com/KnightsOfTheRemoteTable/chess_app/pull/40
