### ISSUE TITLE
Google Login page in production generates an error

### ISSUE THREAD

**Issue by radiofreemattd** [KnightsOfTheRemoteTable/chess_app#91]
This is the screen I get when I try to click the 'Login with Google' link. Can anyone else verify?

![screen shot 2015-12-14 at 1 15 02 pm](https://cloud.githubusercontent.com/assets/10587273/11794170/cc3cbaee-a264-11e5-91d6-ca50d842a182.png)

**Comment by jonmast** [comment]
I didn't set up the ENV variables on Heroku :frowning:

**Comment by mscoutermarsh** [comment]
love it :)

**Comment by mscoutermarsh** [comment]
btw. I recommend using `fetch` for env vars if you can. Then the app won't start without them.

more info: http://michalorman.com/2015/02/fetch-your-environment-variables/
